version: '3.5'

services:
  postgres:
    container_name: eventstoredb
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
    ports:
      - "5432:5432"
    restart: unless-stopped
  